FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS builder
WORKDIR /app
RUN apk add --no-cache libc6-compat
RUN pnpm add -g turbo
COPY . .
RUN turbo prune @syncora/workers --out=out

FROM base AS installer
WORKDIR /app
COPY --from=builder /app/out/json/ .
COPY --from=builder /app/out/pnpm-lock.yaml ./pnpm-lock.yaml
RUN pnpm install --frozen-lockfile

COPY --from=builder /app/out/full/ .
COPY turbo.json turbo.json
RUN pnpm build --filter=@syncora/workers

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=installer /app/ .

CMD ["pnpm", "--filter", "@syncora/workers", "start"]
